apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chaos
  namespace: kube-system
  labels: 
    name: "chaos"
    chaos: "on"
spec:
  selector:
    matchLabels:
      name: "chaos"
  template:
    metadata:
      labels:
        name: "chaos"
    spec:
      nodeSelector:
        chaos: "on"
      containers:
      - name: chaos
        securityContext:
          privileged: true
        image: kube-chaos:v0.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: etckubernetes
          mountPath: /etc/kubernetes
        - name: varlibkubelet
          mountPath: /var/lib/kubelet
        - name: libmodules
          mountPath: /lib/modules
        - name: host-time
          mountPath: /etc/localtime
        - name: log
          mountPath: /tmp
       # command:
       # - kube-chaos
       # - --etcd-endpoint=http://10.96.232.136:6666
       # - --labelSelector=chaos=open
       # - --v=4
      volumes:
      - name: etckubernetes
        hostPath:
          path: /etc/kubernetes
      - name: varlibkubelet
        hostPath:
          path: /var/lib/kubelet
      - name: libmodules
        hostPath:
          path: /lib/modules
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: log
        hostPath:
          path: /tmp
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
